name: build - deploy
run-name: ${{ github.actor }} is building and deploying
on: workflow_dispatch
jobs:
  create-cert-key-files:
    runs-on: self-hosted
    steps:
      - name: create-private-key-file
        uses: actions/checkout@v4
        env:
          PRIVKEY: ${{secrets.PRIVKEY}}
          FULLCHAIN: ${{secrets.FULLCHAIN}}
      - run: | 
          touch privkey.pem
          echo "${{secrets.PRIVKEY}}" > privkey.pem
          touch fullchain.pem
          echo "${{secrets.FULLCHAIN}}" > fullchain.pem 
  build-image:
    needs: create-cert-key-files
    runs-on: self-hosted
    steps:
      - run: |
          touch notes.txt
          echo "this is a test" > notes.txt
          grep -Fx "this is a test" notes.txt
      - name: build image
        uses: docker/setup-buildx-action@v3
      - run: docker build -t pong-game .

  run:
    needs: build-image
    runs-on: self-hosted
    steps:
      - run: | 
          docker stop pong
          docker rm pong
          docker run --name pong -dp "${{vars.IP}}:443:443" pong-game
          echo "y" | docker container prune
          echo "y" | docker image prune